# Generated by Django 5.1.1 on 2024-10-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_add_edit_Author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='course_author',
        ),
        migrations.AddField(
            model_name='course',
            name='course_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.author'),
        ),
    ]
